services:
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    adminer:
        image: adminer
        ports:
            - 9090:8080
        depends_on:
        - db

    mail:
        image: axllent/mailpit:latest
        ports:
        - 8025:8025
        - 1025:1025
        
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379
        
    db:
        image: postgres:16
        ports:
            - 5432:5432
        volumes:
            - .docker/db/data:/var/lib/postgresql/data
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=refactorian
            - POSTGRES_PASSWORD=refactorian
            - POSTGRES_DB=refactorian

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 5050:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
        depends_on:
            - db
